version: '3.8'

services:
  backend:
    build:
      context: ./mern/backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production  
    ports:
      - "5050:5050"
    networks:
      - mern
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
      NODE_ENV: production
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always  # automatic restart on failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]  
      interval: 30s  
      retries: 3  
      timeout: 10s  

  frontend:
    build:
      context: ./mern/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_MODE: production
    ports:
      - "5173:5173"
    networks:
      - mern
    environment:
      REACT_APP_API_URL: http://backend:5050
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]  
      interval: 30s  
      retries: 3  
      timeout: 10s  

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet  
      interval: 30s  
      retries: 3  
      timeout: 10s  

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local








