services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  frontend:
    build: ./mern/frontend
    ports:
      - "4173:4173"  # Port changed to 4173 for Vite's preview server
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050
    depends_on:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1G"

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local








